language : cpp
compiler:
  - g++
before_install:
  - echo $LANG
  - echo $LC_ALL
install:
    #GCC
    - sudo apt-get install gcc-4.9
    # SDL2
    - curl -O http://www.libsdl.org/release/SDL2-2.0.0.zip
    - unzip SDL2-2.0.0.zip
    - (cd SDL2-2.0.0 && ./configure && make && sudo make install)
    - cd ..
    - curl -O http://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.0.zip
    - unzip SDL2_mixer-2.0.0.zip
    - (cd SDL2_mixer-2.0.0 && ./configure && make && sudo make install)
    - cd ..
    - curl -O http://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.0.zip
    - unzip SDL2_image-2.0.0.zip
    - (cd SDL2_image-2.0.0 && ./configure && make && sudo make install)
    - curl -O http://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.12.zip
    - unzip SDL2_ttf-2.0.12.zip
    - (cd SDL2_ttf-2.0.12 && ./configure && make && sudo make install)
    - cd ..
    - pwd
before_script: cd /home/travis/build/richerarc/Projet-SIM/sources/Classes\ projet/
script: make
branches:
  only:
    - master
notifications:
  recipients:
    - richer.arc@gmail.com
  email:
    on_success: change
    on_failure: change
    on_errored: change
os:
  - linux
  
#env:
#   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
#   #   via the "travis encrypt" command using the project repo's public key
#   - secure: "U7I3/UuJnp1d5dmqBUs1ZLZl/n+IPIEUsnevu6BaANFAIEXBbrX59wn7P5An5eT3N/ORt+IDrRPH2hMZulLzMsv3hFhycClOLFH0qVB0WY1AgYdoFqUsSimIEPnGiHg1jVQPy35KDkdvieyhHZXnlTC4ybsW/ZVHolLljKQBFzI="
#
#addons:
#  coverity_scan:
#    project:
#      name: "richerarc/Projet-SIM"
#      description: "<Your project description here>"
#    notification_email: richer.arc@gmail.com
#    #build_command_prepend: "<Your build preprocessing command here>"
#    build_command:   "make"
#    branch_pattern: master
